name: 'terraform-plan-poster'
description: 'Formats and posts a terraform plan on a pull request'
inputs:
  github-token:
    required: true
    type: secure
  plan-file:
    description: 'terraform plan (text)'
    required: true
  pull-request-number:
    description: 'pull request number'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --plan-file=${{ inputs.plan-file }}
    - --pull-request-number=${{ inputs.pull-request-number }}
    - --github-token=${{ inputs.github-token }}
outputs:
  add:
    description: 'Number of resources to add'
  change:
    description: 'Number of resources to change'
  destroy:
    description: 'Number of resources to destroy'
